name: whoami
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]

jobs:
  publish_to_ecr:
    runs-on: basic-k8s-runner
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.2
      - name: whoami
        run: |
          aws sts get-caller-identity 
          aws s3 ls
