name: build and push Redash image

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        default: 'latest'
        description: Which image-tag to use

jobs:
  publish_to_ecr:
    name: publish image to ECR
    secrets: inherit
    uses: careem/shared-workflows/.github/workflows/python.yml@master
    with:
      python-version: "3.9"
      test-command: "aws sts get-caller-identity"
