name: build and push Redash image

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]
  

jobs:
  publish_to_ecr:
    name: publish image to ECR
    secrets: inherit
    uses: careem/shared-workflows/.github/workflows/python.yml@master
    with:
      python-version: "3.9"
      test-command: "aws sts get-caller-identity"
