name: build and push Redash image

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]
  

jobs:
  publish_to_ecr:
    name: publish image to ECR
    secrets: inherit
    uses: careem/shared-workflows/.github/workflows/golang.yml@master
    with:
      build-cmd: "aws sts get-caller-identity"
      test-cmd: "aws sts get-caller-identity"
      go-version: '^1.13.1'
